### ISSUE TITLE
 Cannot find module 'fs/promises'

### ISSUE THREAD

**Issue by ixiDev** [whalemare/action-dropbox#74]
Hi, thanks fro this project .
I am trying to upload a file to my Dropbox

her is my config:

```yaml

      - name: Dropbox Uploader
        uses: whalemare/action-dropbox@v1.0.0
        with:
          file: "./build/dist/*.exe"
          accessToken: "my-access-token"
          destination: 'my-dir'
          displayProgress: true

```

Error: Cannot find module 'fs/promises'

**Require stack:**
```
- D:\a\_actions\whalemare\action-dropbox\v1.0.0\dist\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.9225 (D:\a\_actions\whalemare\action-dropbox\v1.0.0\webpack:\dropbox-uploader\external "fs\promises":1:1)
    at __webpack_require__ (D:\a\_actions\whalemare\action-dropbox\v1.0.0\webpack:\dropbox-uploader\webpack\bootstrap:20:1)
    at Object.3109 (D:\a\_actions\whalemare\action-dropbox\v1.0.0\webpack:\dropbox-uploader\lib\main.js:31:1)
    at __webpack_require__ (D:\a\_actions\whalemare\action-dropbox\v1.0.0\webpack:\dropbox-uploader\webpack\bootstrap:20:1)
    at D:\a\_actions\whalemare\action-dropbox\v1.0.0\webpack:\dropbox-uploader\webpack\startup:4:1
    at Object.<anonymous> (D:\a\_actions\whalemare\action-dropbox\v1.0.0\dist\index.js:14853:12)
```
